name: Workflow

on:
  pull_request:

jobs:
  code-quality:
    name: Run check code quality
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install project
        run: npm install

      - name: Run Linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: print secret
        run: echo "my secret ${{ secrets.DOCKERHUB_USERNAME }}"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/githup-api
          tags: main
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
